# just wait for PR to run on main as a tirgger
pr: none
trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2
  pipelines:
    - pipeline: pr
      source: PR
      trigger:
        branches:
          include:
            - main

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    gitFetchDepth: 0
    globalVariables:
      - template: .azure/pipelines/azure-pipelines-variables.yml@self
    validationJobs:
      - name: Docker Build DCO Portal
        steps:
          - template: ../steps/azure_web_app_docker_build_push.yml@templates
            parameters:
              azurecrName: $(azurecrName)
              dockerfilePath: $(Build.SourcesDirectory)/apps/portal/Dockerfile
              repository: applications/dco-portal
              buildArgs:
                - GIT_SHA=$(Build.SourceVersion)
      - name: Docker Build Pdf Service api
        steps:
          - template: ../steps/azure_web_app_docker_build_push.yml@templates
            parameters:
              azurecrName: $(azurecrName)
              dockerfilePath: $(Build.SourcesDirectory)/apps/pdf-service-api/Dockerfile
              repository: applications/dco-pdf-service-api
              buildArgs:
                - GIT_SHA=$(Build.SourceVersion)
      - name: Function Build
        steps:
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm ci --omit=dev --workspace=dco-portal-function --workspace=@pins/dco-portal-database --workspace=@pins/dco-portal-lib
              workingDirectory: $(Build.Repository.LocalPath)
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm run db-generate
              workingDirectory: $(Build.Repository.LocalPath)
          - script: |
              source ~/.bashrc
              # copy root node_modules to function (but don't overwrite)
              rsync -a -r --ignore-existing $(Build.Repository.LocalPath)/node_modules/ $(Build.Repository.LocalPath)/apps/function/node_modules/
              # ensure there is a dco-portal-database folder (matches package imports)
              mkdir -p $(Build.Repository.LocalPath)/apps/function/src/packages/dco-portal-database
              # ensure there is a dco-portal-lib folder (matches package imports)
              mkdir -p $(Build.Repository.LocalPath)/apps/function/src/packages/dco-portal-lib
              # copy db package to packages/dco-portal-database folder
              cp -r $(Build.Repository.LocalPath)/packages/database/* $(Build.Repository.LocalPath)/apps/function/src/packages/dco-portal-database/
              # copy lib package to packages/dco-portal-lib folder
              cp -r $(Build.Repository.LocalPath)/packages/lib/* $(Build.Repository.LocalPath)/apps/function/src/packages/dco-portal-lib/
              # remove the package files to avoid subpath import issues - treat them as part of the functions code src
              rm -f $(Build.Repository.LocalPath)/apps/function/src/packages/dco-portal-database/package.json
              rm -f $(Build.Repository.LocalPath)/apps/function/src/packages/dco-portal-lib/package.json
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              # we do this after the above copy step so that the replacements can also apply to the packages themselves
              script: npm run prepare-package
              workingDirectory: $(Build.Repository.LocalPath)/apps/function
          - task: ArchiveFiles@2
            displayName: Archive files
            inputs:
              rootFolderOrFile: $(Build.Repository.LocalPath)/apps/function
              includeRootFolder: false
              archiveFile: $(System.DefaultWorkingDirectory)/functions.zip
          - publish: $(System.DefaultWorkingDirectory)/functions.zip
            artifact: function-integration
            displayName: Publish Functions Artifact
