parameters:
  - name: schemaMigration
    displayName: Run SQL Database Migration
    type: boolean
    default: true
  - name: deployPortal
    displayName: Deploy Portal
    type: boolean
    default: true
  - name: deployPdf
    displayName: Deploy PDF Service API
    type: boolean
    default: true
  - name: deployFunctionIntegration
    displayName: Deploy Function - Integration
    type: boolean
    default: true

pr: none
trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2
  pipelines:
    - pipeline: build
      source: Build
      trigger:
        branches:
          include:
            - main

extends:
  template: stages/wrapper_cd.yml@templates
  parameters:
    variableGroupPrefix: 'cd'
    environments:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Training
        dependsOn:
          - Test
      - name: Prod
        dependsOn:
          - Training
    globalVariables:
      - template: .azure/pipelines/azure-pipelines-variables.yml@self
    deploymentStages:
      - name: Stage
        deploymentJobs:
          - name: Stage DCO Portal
            condition: ${{ eq(parameters.deployPortal, true) }}
            steps:
              - template: ../steps/azure_web_app_deploy_slot.yml@templates
                parameters:
                  appName: pins-app-dco-portal-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  azurecrName: $(azurecrName)
                  repository: applications/dco-portal
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: Portal
                  appUrl: $(deploySlotOutputs.slotUrl)/health
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  appRegistrationClientId: $(PORTAL_APP_REGISTRATION_ID)
                  auth_enabled: 'true'
                  env: $(ENVIRONMENT)
          - name: Stage DCO Pdf Service API
            condition: ${{ eq(parameters.deployPdf, true) }}
            steps:
              - template: ../steps/azure_web_app_deploy_slot.yml@templates
                parameters:
                  appName: pins-app-dco-pdf-service-api-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  azurecrName: $(azurecrName)
                  repository: applications/dco-pdf-service-api
              - template: ../steps/azure_web_app_verify_git_hash.yml@templates
                parameters:
                  appName: Pdf Service API
                  appUrl: $(deploySlotOutputs.slotUrl)/health
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  auth_enabled: 'false'
                  env: $(ENVIRONMENT)
      - name: Deploy
        dependsOn:
          - Stage
        deploymentJobs:
          - name: Migrate
            condition: ${{ eq(parameters.schemaMigration, true) }}
            steps:
              - checkout: self
              - template: ../steps/azure_get_secrets.yml@templates
                parameters:
                  keyVaultName: pins-kv-dcop-$(ENVIRONMENT)
                  secrets:
                    - name: dcop-sql-admin-connection-string
                      variable: SQL_CONNECTION_STRING_ADMIN
                    - name: dcop-sql-app-connection-string
                      variable: SQL_CONNECTION_STRING
              - template: ../steps/node_script.yml@templates
                parameters:
                  nodeVersion: 22
                  script: npm ci --workspace=@pins/dco-portal-database
                  workingDirectory: $(Build.Repository.LocalPath)
              - ${{ if eq(parameters.schemaMigration, true) }}:
                  - template: ../steps/node_script.yml@templates
                    parameters:
                      nodeVersion: 22
                      environmentVariables:
                        SQL_CONNECTION_STRING_ADMIN: $(SQL_CONNECTION_STRING_ADMIN)
                      script: npm run migrate-prod
                      workingDirectory: $(Build.Repository.LocalPath)/packages/database
          - name: Deploy DCO Portal
            condition: ${{ eq(parameters.deployPortal, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-dco-portal-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: DCO Portal
                  appUrl: https://pins-app-dco-portal-$(ENVIRONMENT).azurewebsites.net/health
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  appRegistrationClientId: $(PORTAL_APP_REGISTRATION_ID)
                  auth_enabled: 'true'
                  env: $(ENVIRONMENT)
          - name: Deploy DCO Pdf Service API
            condition: ${{ eq(parameters.deployPdf, true) }}
            steps:
              - template: ../steps/azure_web_app_slot_swap.yml
                parameters:
                  appName: pins-app-dco-pdf-service-api-$(ENVIRONMENT)
                  appResourceGroup: $(resourceGroup)
                  appStagingSlotName: staging
                  appTargetSlotName: production
              - template: ../steps/azure_web_app_verify_git_hash.yml
                parameters:
                  appName: DCO Pdf Service API
                  appUrl: https://pins-app-dco-pdf-service-api-$(ENVIRONMENT).azurewebsites.net/health
                  buildCommit: $(resources.pipeline.build.sourceCommit)
                  auth_enabled: 'false'
                  env: $(ENVIRONMENT)
          - name: Deploy Integration Functions
            condition: ${{ eq(parameters.deployFunctionIntegration, true) }}
            steps:
              - download: build
                artifact: function-integration
                displayName: Download function-integration
              - template: ../steps/function_app_deploy.yml
                parameters:
                  appName: pins-func-dcop-function-integration-$(ENVIRONMENT)
                  resourceGroup: $(resourceGroup)
                  workingDirectory: $(Pipeline.Workspace)/build/function-integration
